# BÀI TẬP TRÊN LỚP

Bài 1.1


In [1]:
import numpy as np
n = 4
X = np.array(range(1,n+1))
sigma = np.array([4,3,2,1])
def sgn_by_def(sigma):
  ketqua = 1.0
  for i in range(len(X)-1):
      for j in range(i+1,len(X)):
        ketqua = ketqua * ((X[i]-X[j])/ (sigma[i]-sigma[j]))
      return int(ketqua)
sigma = np.array([2,1,3,4])
sgn_by_def(sigma)


-3

Bài 1.2


In [2]:
import numpy as np
n = 4
X = np.array(range(1,n+1))
sigma = np.array([4,3,2,1])
def sgn_by_def(sigma):
  ketqua = 1.0
  for i in range(len(X)-1):
      for j in range(i+1,len(X)):
        ketqua = ketqua * ((X[i]-X[j])/ (sigma[i]-sigma[j]))
      return int(ketqua)
sigma = np.array([1,2,3,4])
sgn_by_def(sigma)

1

Bài 1.3

In [3]:
import numpy as np
n = 4
X = np.array(range(1,n+1))
sigma = np.array([4,3,2,1])
def sgn_by_def(sigma):
  ketqua = 1.0
  for i in range(len(X)-1):
      for j in range(i+1,len(X)):
        ketqua = ketqua * ((X[i]-X[j])/ (sigma[i]-sigma[j]))
      return int(ketqua)
sigma = np.array([4,3,2,1])
sgn_by_def(sigma)

-1

Bài 2.1


In [6]:
from itertools import permutations
n = 3
X = []
for i in range (1, n+1):
  X.append(i)
Sn = list(permutations(X)) #  tạo hoán vị của tập X
print (Sn)
det = 0
def sgn_by_def(sigma):
    n = len(sigma)
    count = 0
    for i in range(n):
        for j in range(i+1, n):
            if sigma[i] > sigma[j]:
                count += 1
    return -1 if count % 2 == 1 else 1


[(1, 2, 3), (1, 3, 2), (2, 1, 3), (2, 3, 1), (3, 1, 2), (3, 2, 1)]


Bài 2.2

In [8]:
import numpy as np
def sgn_by_def(sigma):
    n = len(sigma)
    count = 0
    for i in range(n):
        for j in range(i+1, n):
            if sigma[i] > sigma[j]:
                count += 1
    return -1 if count % 2 == 1 else 1
def phatsinh_dinhthuc(n):
        X = []
        for i in range(1, n+1):
            X.append(i)

        Sn = list(permutations(X))    # Tạo tập các hoán vị
        dinhthuc = ""

        for sn in Sn:
            sigma = np.array([1])
            sigma.resize([n])
            product = ""

            for i in range(1, n+1):
                sigma[sn.index(i)] = i
                product = product + "a" + str(i) + str(sn.index(i)+1)

            dau = sgn_by_def(sigma)   # Hàm tính dấu của hoán vị sigma

            if (dau != 1):
                product = " - " + product
            else:
                product = " + " + product

            dinhthuc = dinhthuc + product

        return dinhthuc
kq = phatsinh_dinhthuc(2)
ketqua = phatsinh_dinhthuc(3)
print(kq)
print(ketqua)

 + a11a22 - a12a21
 + a11a22a33 - a11a23a32 - a12a21a33 + a13a21a32 + a12a23a31 - a13a22a31


Bài 2.3

In [10]:
import numpy as np
def tinhtoan_dinhthuc(A):
    X = []
    import math  # dùng để lấy căn bậc hai

    n = int(math.sqrt(A.size))  # kích thước ma trận vuông: sqrt(số phần tử)

    for i in range(1, n+1):
        X.append(i)

    Sn = list(permutations(X))   # tạo tập các hoán vị
    dinhthuc = 0                 # khởi tạo giá trị định thức

    for sn in Sn:
        sigma = np.array([1])
        sigma.resize([n])
        product = 1              # khởi tạo tích các phần tử

        for i in range(1, n+1):
            sigma[sn.index(i)] = i
            product = product * A[i-1][sn.index(i)]  # chỉ số i-1 vì Python đếm từ 0

        dau = sgn_by_def(sigma)   # tính dấu của hoán vị

        if dau != 1:
            product = product * (-1)

        dinhthuc = dinhthuc + product

    return dinhthuc
matrann = np.array([
    [3, 5, -8],
    [4, 12, -1],
    [2, 5, 3]
])
kq = tinhtoan_dinhthuc(matrann)
print(kq)

85


Bài 3

In [5]:
import numpy as np
A = np.array([[4, -2],[3, -5]]) # khai báo ma trận A
A1 = np.array([[10, -2],[11, -5]])
A2 = np.array([[4, 10],[3, 11]])
from scipy import linalg # lưu ý: hàm tính định thức của ma trận là scipy.linalg.det(A)
detA = linalg.det(A) # tính định thức cho ma trận A
detA1 = linalg.det(A1)
11
detA2 = linalg.det(A2)
print (detA, detA1, detA2)

if (detA != 0):
 x1 = detA1 / detA
 x2 = detA2 / detA
 print ("Hai nghiệm của phương trình là: ", x1, x2)

-14.0 -28.0 14.000000000000004
Hai nghiệm của phương trình là:  2.0 -1.0000000000000002


Bài 3.1 Tính det(A)

In [12]:
import numpy as np
def tinhtoan_dinhthuc(A):
    X = []
    import math

    n = int(math.sqrt(A.size))

    for i in range(1, n+1):
        X.append(i)

    Sn = list(permutations(X))
    dinhthuc = 0

    for sn in Sn:
        sigma = np.array([1])
        sigma.resize([n])
        product = 1

        for i in range(1, n+1):
            sigma[sn.index(i)] = i
            product = product * A[i-1][sn.index(i)]

        dau = sgn_by_def(sigma)

        if dau != 1:
            product = product * (-1)

        dinhthuc = dinhthuc + product

    return dinhthuc
A = np.array([[4, -2],[3, -5]])

kq = tinhtoan_dinhthuc(A)
print(kq)

-14


Bài 3.2 tính det(A1)

In [13]:
import numpy as np
def tinhtoan_dinhthuc(A):
    X = []
    import math

    n = int(math.sqrt(A.size))

    for i in range(1, n+1):
        X.append(i)

    Sn = list(permutations(X))
    dinhthuc = 0

    for sn in Sn:
        sigma = np.array([1])
        sigma.resize([n])
        product = 1

        for i in range(1, n+1):
            sigma[sn.index(i)] = i
            product = product * A[i-1][sn.index(i)]

        dau = sgn_by_def(sigma)

        if dau != 1:
            product = product * (-1)

        dinhthuc = dinhthuc + product

    return dinhthuc
A1 = np.array([[10, -2],[11, -5]])

kq = tinhtoan_dinhthuc(A1)
print(kq)

-28


Bài 3.3 tính det(A2)


In [14]:
import numpy as np
def tinhtoan_dinhthuc(A):
    X = []
    import math

    n = int(math.sqrt(A.size))

    for i in range(1, n+1):
        X.append(i)

    Sn = list(permutations(X))
    dinhthuc = 0

    for sn in Sn:
        sigma = np.array([1])
        sigma.resize([n])
        product = 1

        for i in range(1, n+1):
            sigma[sn.index(i)] = i
            product = product * A[i-1][sn.index(i)]

        dau = sgn_by_def(sigma)

        if dau != 1:
            product = product * (-1)

        dinhthuc = dinhthuc + product

    return dinhthuc
A2 = np.array([[4, 10],[3, 11]])

kq = tinhtoan_dinhthuc(A2)
print(kq)

14


Bài 5


In [17]:
import sympy as sp
TG = sp.Matrix([[1, 0, 1],[4, 3, 1], [2, 2, 1]])
print('kết quả diện tích tam giác là:',1/2*TG.det())

kết quả diện tích tam giác là: 1.50000000000000


Bài 5.1


In [20]:
import sympy as sp
M = sp.Matrix([[0, 4, 1, 1], [4, 0, 0, 1], [3, 5, 2, 1], [2, 2,
5, 1]])
print(M.det())
print('thể tích tứ diện là:',1/6*M.det())

-72
thể tích tứ diện là: -12.0000000000000


Bài 5.2


In [26]:
from sympy import * # lúc này ta sử dụng trực tiếp thư viện
x, y, z = symbols('x y z')

MP = Matrix([[x, y, z, 1],[-1, 3, 2, 1],[0, 1, 0, 1],[-2, 0,
1, 1]])

MP.det()

-4*x + 3*y - 5*z - 3

# BÀI TẬP VỀ NHÀ

Bài 1

In [27]:
import numpy as np

# Hàm tính định thức con bằng cách loại bỏ hàng i và cột j
def minor(matrix, i, j):
    sub_matrix = np.delete(np.delete(matrix, i, axis=0), j, axis=1)
    return round(np.linalg.det(sub_matrix))  # Làm tròn định thức nhỏ

# Hàm tính ma trận hệ số kép (cofactor matrix)
def cofactor_matrix(A):
    n = A.shape[0]
    cof = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            cof[i, j] = ((-1) ** (i + j)) * minor(A, i, j)
    return cof

# Hàm tính ma trận liên hợp (adjoint matrix)
def adjoint_matrix(A):
    cof = cofactor_matrix(A)
    adj = cof.T  # Chuyển vị của ma trận hệ số kép
    return adj
A = np.array([[2, -1, 0], [1, 3, -2], [0, 5, 1]])

cof = cofactor_matrix(A)
adj = adjoint_matrix(A)

print("Ma trận hệ số kép (cofactor matrix):\n", cof)
print("Ma trận liên hợp (adjoint matrix):\n", adj)


Ma trận hệ số kép (cofactor matrix):
 [[ 13.  -1.   5.]
 [  1.   2. -10.]
 [  2.   4.   7.]]
Ma trận liên hợp (adjoint matrix):
 [[ 13.   1.   2.]
 [ -1.   2.   4.]
 [  5. -10.   7.]]


Bài 2


In [28]:
from sympy import symbols, Matrix, simplify, Eq, solve

# Khai báo biến x, y là tọa độ cần tìm
x, y = symbols('x y')

# Nhập vào tọa độ 3 điểm
x1, y1 = 1, 1
x2, y2 = 2, 4
x3, y3 = 5, 3

# Xây dựng ma trận theo hướng dẫn
M = Matrix([
    [x**2 + y**2, x, y, 1],
    [x1**2 + y1**2, x1, y1, 1],
    [x2**2 + y2**2, x2, y2, 1],
    [x3**2 + y3**2, x3, y3, 1],
])

# Tính định thức
det = M.det()

# Rút gọn và hiển thị phương trình đường tròn
circle_eq = simplify(det)
print("Phương trình đường tròn là:")
print(Eq(circle_eq, 0))


Phương trình đường tròn là:
Eq(-10*x**2 + 60*x - 10*y**2 + 40*y - 80, 0)
