# BÀI TẬP TRÊN LỚP


Bài 1:

In [12]:
from scipy import linalg
import numpy as np
a = np.array([1, 2, 3])
b = np.array([(1+9j, 2j, 3j), (4j, 5j, 6j)]) # số phức
c = np.array([[ (0.5, 1.5, 10), (3,2,1) ] , [(6,5,4), (7,8,9)]]) # ma trận số thực

A = np.matrix(np.random.random( (2,2) ) )
B = np.asmatrix(b) # Chuyển b thành dạng ma trận
C = np.matrix(np.random.random( (10,5) ) )
D = np.matrix([ [4, 3], [2, 6] ])
F = np.eye(3, k=1)
F1= np.eye(3,k=0)
F2 = np.eye(3,k=-1)
print(A)
print()
print(B)
print()
print(C)
print()
print(D)
print()
print(F)
print()
print(F1)
print()
print(F2)

[[0.37439442 0.27451606]
 [0.32263568 0.98520757]]

[[1.+9.j 0.+2.j 0.+3.j]
 [0.+4.j 0.+5.j 0.+6.j]]

[[0.68551413 0.22169021 0.98007883 0.63081758 0.11590424]
 [0.81653132 0.99353288 0.33304206 0.88916738 0.37668758]
 [0.9933554  0.19502131 0.15712988 0.23068128 0.10615953]
 [0.76528872 0.17199769 0.39163872 0.54772012 0.0707203 ]
 [0.40292316 0.57132108 0.05278056 0.76873234 0.88609007]
 [0.65609376 0.99544024 0.51990204 0.30037499 0.1757005 ]
 [0.0646304  0.44118622 0.10685933 0.84824164 0.31592953]
 [0.33244825 0.99900876 0.79979058 0.26218599 0.00809081]
 [0.27209956 0.41751776 0.11189998 0.12944082 0.83646288]
 [0.7154774  0.58978952 0.98262667 0.37757062 0.54778312]]

[[4 3]
 [2 6]]

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


Bài 2:


In [10]:
from scipy import linalg
import numpy as np
A = np.matrix(np.random.random((2,2)))
C = np.matrix(np.random.random((10,5)))
rankC = np.linalg.matrix_rank(C)
ND = A.I
DT = linalg.det(A)
CV = A.T
CVLH = A.H
print(rankC)
print()
print(ND)
print()
print(DT)
print()
print(CV)
print()
print(CVLH)

5

[[ 2.33156221 -0.46464342]
 [-2.32531445  1.84655512]]

0.3100855877816562

[[0.57259013 0.7210465 ]
 [0.14407923 0.72298384]]

[[0.57259013 0.7210465 ]
 [0.14407923 0.72298384]]


Bài 3:


In [15]:
from scipy import linalg
from sympy import solve
import numpy as np
a = np.array([1, 2, 3])
b = np.array([(1+9j, 2j, 3j), (4j, 5j, 6j)])
A = np.matrix(np.random.random((2,2)))
F = np.eye(3, k=1)

print(linalg.solve(A,b))
E = np.matrix(a).T
print( linalg.lstsq(F, E) )

[[ 2.04133918+12.80332878j  0.         -2.87822643j
   0.         -2.22906821j]
 [-0.53590236 +3.10056078j  0.         +8.83279778j
   0.        +10.27781592j]]
(array([[0.],
       [1.],
       [2.]]), array([], dtype=float64), 2, array([1., 1., 0.]))


Bài 4:

In [17]:
from scipy import linalg
import numpy as np
A = np.matrix(np.random.random((2,2)))
D = np.matrix([ [4, 3], [2, 6] ])
# Cộng hai ma trận
print('Phép cộng')
print(np.add(A,D))
# Trừ hai ma trận
print('phép trừ')
print(np.subtract(A,D))
# Nhân hai ma trận
print('Phép nhân')
print(A@D)
print(np.multiply(D,A))
print(np.dot(A,D))
print(np.vdot(A,D))
# Hàm luỹ thừa và log ma trận
print('Luỹ thừa và log')
print(linalg.expm(A))
print(linalg.logm(A))

Phép cộng
[[4.4442388  3.51335302]
 [2.46971652 6.01782085]]
phép trừ
[[-3.5557612  -2.48664698]
 [-1.53028348 -5.98217915]]
Phép nhân
[[2.80366124 4.41283451]
 [1.91450777 1.51607464]]
[[1.7769552  1.54005905]
 [0.93943304 0.10692508]]
[[2.80366124 4.41283451]
 [1.91450777 1.51607464]]
[[1.7769552]]
Luỹ thừa và log
[[1.72642284 0.67811043]
 [0.62046907 1.16314873]]
[[-0.54397599+0.94519737j  0.44284246-1.50628325j]
 [ 0.40519956-1.3782448j  -0.91182417+2.19639528j]]


Bài 5:

In [23]:
import numpy as np
# tính ma trận A
A = np.array([[1,0],[0,1]])
print('Ma trận A',A)
temp = A.dot(A)
print('tính toán lần 1:',temp)
k = 6
for i in range(k-1):
  temp = temp.dot(A)
  print(temp)
  print('---')


Ma trận A [[1 0]
 [0 1]]
tính toán lần 1: [[1 0]
 [0 1]]
[[1 0]
 [0 1]]
---
[[1 0]
 [0 1]]
---
[[1 0]
 [0 1]]
---
[[1 0]
 [0 1]]
---
[[1 0]
 [0 1]]
---


Bài 6:

In [26]:
 # tính ma trận B
import numpy as np
B= np.array([[0,-1],[-1,0]])
print('Ma trận B',B)
temp = B.dot(B)
print('tính toán lần 1:',temp)
k = 5
for i in range(k-1):
  temp = temp.dot(B)
  print(temp)
  print('---')

Ma trận B [[ 0 -1]
 [-1  0]]
tính toán lần 1: [[1 0]
 [0 1]]
[[ 0 -1]
 [-1  0]]
---
[[1 0]
 [0 1]]
---
[[ 0 -1]
 [-1  0]]
---
[[1 0]
 [0 1]]
---


Bài 7:


In [27]:
import numpy as np
C = np.array([ [1, 0, 0], [0, 0.5, 1], [0, 0, 0.5] ])
print(C)

temp = C.dot(C) # tính toan lần thứ 1
print(temp)
k= 1000
for i in range(k-1):
  temp = temp.dot(C)
print(temp)


k= 1000
for i in range(k-1):
 temp = temp.dot(C)
print(temp)

[[1.  0.  0. ]
 [0.  0.5 1. ]
 [0.  0.  0.5]]
[[1.   0.   0.  ]
 [0.   0.25 1.  ]
 [0.   0.   0.25]]
[[1.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 4.66631809e-302 9.34196882e-299]
 [0.00000000e+000 0.00000000e+000 4.66631809e-302]]
[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Bài 8:

In [28]:
import numpy as np
M = np.array([ [0.8, 0.3], [0.2, 0.7]])
MM = M.dot(M) # tính M2, nghĩa là M2
print (MM)

MM = M.dot(M) # tính M3
print (MM)

for i in range(100): # tính các M^ khác.
 MM = MM.dot(M)
print (MM) # kết luận xu hướng của jb

[[0.7  0.45]
 [0.3  0.55]]
[[0.7  0.45]
 [0.3  0.55]]
[[0.6 0.6]
 [0.4 0.4]]


Bài 9:


In [29]:
import numpy as np
M = np.array([ [0.5, 0.5], [0.5, 0.5]])
MM = M.dot(M) # tính M2, nghĩa là M2
print (MM)

MM = M.dot(M) # tính M3
print (MM)

for i in range(100): # tính các M^ khác.
 MM = MM.dot(M)
print (MM) # kết luận xu hướng của jb

[[0.5 0.5]
 [0.5 0.5]]
[[0.5 0.5]
 [0.5 0.5]]
[[0.5 0.5]
 [0.5 0.5]]


Bài 10:

In [30]:
from scipy import linalg
import numpy as np
M = np.array([ [0.8, 0.3], [0.2, 0.7]])
P, L, U = linalg.lu(M)
print(P)
print(L)
print(U)
print(L.dot(U))

[[1. 0.]
 [0. 1.]]
[[1.   0.  ]
 [0.25 1.  ]]
[[0.8   0.3  ]
 [0.    0.625]]
[[0.8 0.3]
 [0.2 0.7]]


Bài 11:


In [31]:
import numpy as np
A = np.array([ [0,1,0,1],[0,0,1,0],[1,0,0,1],[1,1,0,0]])
temp = A.dot(A)

print(temp)

temp = temp.dot(A)
print(temp)

[[1 1 1 0]
 [1 0 0 1]
 [1 2 0 1]
 [0 1 1 1]]
[[1 1 1 2]
 [1 2 0 1]
 [1 2 2 1]
 [2 1 1 1]]


Bài 12:


In [33]:
import numpy as np
A = np.array([ [0,1,0,1],[0,0,1,0],[1,0,0,1],[1,1,0,0]])
sumA = A
temp = A.dot(A)
k = 3
sumA = sumA + temp
for i in range(1, k-1):
 temp = temp.dot(A)
 sumA = sumA + temp
print (temp)
print (sumA)

[[1 1 1 2]
 [1 2 0 1]
 [1 2 2 1]
 [2 1 1 1]]
[[2 3 2 3]
 [2 2 1 2]
 [3 4 2 3]
 [3 3 2 2]]


# BÀI TẬP VỀ NHÀ

Bài 1:

In [34]:
import numpy as np

# a. Tạo một ma trận 3x3 khả nghịch
A = np.array([[2, 1, 1],
              [1, 3, 2],
              [1, 0, 0]])

print("Ma trận A:")
print(A)

# Kiểm tra khả nghịch: ma trận có định thức khác 0
det = np.linalg.det(A)
print("\nĐịnh thức của A:", det)

if det != 0:
    print("→ Ma trận A là khả nghịch.")

    # Tính nghịch đảo
    A_inv = np.linalg.inv(A)
    print("\nNghịch đảo của A:")
    print(A_inv)
else:
    print("→ Ma trận không khả nghịch. Chọn ma trận khác.")

# b. Nhập họ tên hoặc MSSV
text = input("\nNhập họ tên hoặc MSSV của bạn: ")

# c. Mã hóa
# Chuyển chuỗi thành mã ASCII
ascii_vals = [ord(c) for c in text]

# Thêm số 0 để đủ chia hết cho 3
while len(ascii_vals) % 3 != 0:
    ascii_vals.append(0)

# Chuyển thành ma trận 3 dòng (mỗi cột là 1 vector 3 chiều)
ascii_matrix = np.array(ascii_vals).reshape(-1, 3).T

print("\nMa trận mã ASCII (gốc):")
print(ascii_matrix)

# Mã hóa bằng A
encoded = A @ ascii_matrix
print("\nMa trận sau khi mã hóa:")
print(encoded)

# d. Giải mã: nhân với A⁻¹
decoded_matrix = A_inv @ encoded
decoded_matrix = np.round(decoded_matrix).astype(int)  # Làm tròn và chuyển về int

# Chuyển ngược lại chuỗi
decoded_vals = decoded_matrix.T.flatten()
decoded_text = ''.join(chr(val) for val in decoded_vals if val != 0)

print("\nGiải mã (chuỗi gốc):", decoded_text)


Ma trận A:
[[2 1 1]
 [1 3 2]
 [1 0 0]]

Định thức của A: -1.0
→ Ma trận A là khả nghịch.

Nghịch đảo của A:
[[ 0.  0.  1.]
 [-2.  1.  3.]
 [ 3. -1. -5.]]

Nhập họ tên hoặc MSSV của bạn: 9413413946831

Ma trận mã ASCII (gốc):
[[57 51 51 54 49]
 [52 52 57 56  0]
 [49 49 52 51  0]]

Ma trận sau khi mã hóa:
[[215 203 211 215  98]
 [311 305 326 324  49]
 [ 57  51  51  54  49]]

Giải mã (chuỗi gốc): 9413413946831
