# BÀI TẬP TRÊN LỚP


#Bài 1:

In [2]:
def scale(a, v):
  return [a*vi for vi in v]
v = [3,5,7]
print(scale(10, v))


[30, 50, 70]


#Bài 2:


In [3]:
def sumvector(v, w):
 return [vi+wi for (vi, wi) in zip(v, w)]
v = [3,5,7]
w = [2,4,6]
print(sumvector(v, w))

[5, 9, 13]


#Bài 3:


In [4]:
def dotvector(v, w):

 return sum([vi*wi for (vi, wi) in zip(v, w)])
print(dotvector(v, w))

68


#Bài 4:


In [5]:
def lenvector(v):
 return dotvector(v,v)
print(lenvector(w))

56


#Bài 5:

In [11]:
import numpy as np
scores = np.array([-1, 1, 2, -3, 5, -4])
print(scores >=0)
print(scores <0)
print(np.select([scores >= 0, scores < 0], ["so duong", "so am"], default="khong xac dinh"))




[False  True  True False  True False]
[ True False False  True False  True]
['so am' 'so duong' 'so duong' 'so am' 'so duong' 'so am']


#Bài 6:

In [12]:
scores = np.array([-1, 1, 2, 0, -3, 5, 0, -4])
print(np.select([scores >0, scores ==0, scores < 0],['so duong', 'so 0', 'so am'], default="khong xa dinh"))

['so am' 'so duong' 'so duong' 'so 0' 'so am' 'so duong' 'so 0' 'so am']


#Bài 7:

In [15]:
import numpy as np
D = np.asmatrix([[3,4],[5,6]])
print(D)

[[3 4]
 [5 6]]


#Bài 8:

In [18]:
import numpy as np
C = np.asmatrix(np.random.random((5,7)))
print(C)

[[0.91815254 0.77331857 0.16420355 0.46794665 0.94597568 0.48724856
  0.48771557]
 [0.37484886 0.54834458 0.81115585 0.89529056 0.97247062 0.11471496
  0.14316668]
 [0.62129049 0.57670332 0.19465487 0.959244   0.42694962 0.59073743
  0.20592356]
 [0.78101878 0.23388543 0.79321808 0.13600212 0.29409528 0.0920851
  0.56124255]
 [0.81399476 0.47649275 0.3918061  0.63330131 0.43097059 0.1762662
  0.85404948]]


# Bài 9:


In [20]:
import numpy as np
A = np.asmatrix(np.random.random((2,2)))
print (A)

[[0.41291381 0.68103432]
 [0.10160627 0.5341843 ]]


#Bài 10:

In [21]:
import numpy as np
b = np.array([(1+5j, 2j, 3j),(4, 5,6)])
B = np.asmatrix(b)


print (b)
print (B)

[[1.+5.j 0.+2.j 0.+3.j]
 [4.+0.j 5.+0.j 6.+0.j]]
[[1.+5.j 0.+2.j 0.+3.j]
 [4.+0.j 5.+0.j 6.+0.j]]


#Bai 11:

In [1]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6]])
print("Chuyển vị của ma trận:",A.T)


Chuyển vị của ma trận: [[1 4]
 [2 5]
 [3 6]]


#Bài 12:

In [26]:
import numpy as np

A = np.array([[1, 2],
              [3, 4]])

inv_A = np.linalg.inv(A)

print("\nMa trận nghịch đảo của A:")
print(inv_A)



Ma trận nghịch đảo của A:
[[-2.   1. ]
 [ 1.5 -0.5]]


#Bài 13:

In [27]:
import numpy as np
M = np.array([[-1,3,2],[0,-2,1],[1,5,-2]])
M_lower = np.tril(M)
print('Ma trận dưới từ dường chéo:',M_lower)


Ma trận dưới từ dường chéo: [[-1  0  0]
 [ 0 -2  0]
 [ 1  5 -2]]


#Bài 14:

In [28]:
import numpy as np
M = np.array([[-1,3,2],[0,-2,1],[1,5,-2]])
M_upper = np.triu(M)
print('Ma trận trên từ đường chéo:',M_upper)

Ma trận trên từ đường chéo: [[-1  3  2]
 [ 0 -2  1]
 [ 0  0 -2]]


#Bài 15:

In [29]:
import numpy as np
M = np.array([[-1,3,2],[0,-2,1],[1,5,-2]])
v_diag = np.diag(M) #vectorđường chéo
print (v_diag)
M_diag = np.diag(v_diag)
print (M_diag)

[-1 -2 -2]
[[-1  0  0]
 [ 0 -2  0]
 [ 0  0 -2]]


#Bài 16:


In [32]:
from sympy import symbols, solve
x,y,z = symbols('x,y,z')
print(solve([x*x+2-6, y-1-6, x+z-1, 2*x*x-8, z*z+4-5, y-z-8], [x,y,z]))

[(2, 7, -1)]
