# BÀI TẬP TRÊN LỚP


#Bài 1:

In [ ]:
def scale(a, v):
  return [a*vi for vi in v]
v = [3,5,7]
print(scale(10, v))


[30, 50, 70]


#Bài 2:


In [ ]:
def sumvector(v, w):
 return [vi+wi for (vi, wi) in zip(v, w)]
v = [3,5,7]
w = [2,4,6]
print(sumvector(v, w))

[5, 9, 13]


#Bài 3:


In [ ]:
def dotvector(v, w):

 return sum([vi*wi for (vi, wi) in zip(v, w)])
print(dotvector(v, w))

68


#Bài 4:


In [ ]:
def lenvector(v):
 return dotvector(v,v)
print(lenvector(w))

56


#Bài 5:

In [ ]:
import numpy as np
scores = np.array([-1, 1, 2, -3, 5, -4])
print(scores >=0)
print(scores <0)
print(np.select([scores >= 0, scores < 0], ["so duong", "so am"], default="khong xac dinh"))




[False  True  True False  True False]
[ True False False  True False  True]
['so am' 'so duong' 'so duong' 'so am' 'so duong' 'so am']


#Bài 6:

In [ ]:
scores = np.array([-1, 1, 2, 0, -3, 5, 0, -4])
print(np.select([scores >0, scores ==0, scores < 0],['so duong', 'so 0', 'so am'], default="khong xa dinh"))

['so am' 'so duong' 'so duong' 'so 0' 'so am' 'so duong' 'so 0' 'so am']


#Bài 7:

In [ ]:
import numpy as np
D = np.asmatrix([[3,4],[5,6]])
print(D)

[[3 4]
 [5 6]]


#Bài 8:

In [ ]:
import numpy as np
C = np.asmatrix(np.random.random((5,7)))
print(C)

[[0.91815254 0.77331857 0.16420355 0.46794665 0.94597568 0.48724856
  0.48771557]
 [0.37484886 0.54834458 0.81115585 0.89529056 0.97247062 0.11471496
  0.14316668]
 [0.62129049 0.57670332 0.19465487 0.959244   0.42694962 0.59073743
  0.20592356]
 [0.78101878 0.23388543 0.79321808 0.13600212 0.29409528 0.0920851
  0.56124255]
 [0.81399476 0.47649275 0.3918061  0.63330131 0.43097059 0.1762662
  0.85404948]]


# Bài 9:


In [ ]:
import numpy as np
A = np.asmatrix(np.random.random((2,2)))
print (A)

[[0.41291381 0.68103432]
 [0.10160627 0.5341843 ]]


#Bài 10:

In [ ]:
import numpy as np
b = np.array([(1+5j, 2j, 3j),(4, 5,6)])
B = np.asmatrix(b)


print (b)
print (B)

[[1.+5.j 0.+2.j 0.+3.j]
 [4.+0.j 5.+0.j 6.+0.j]]
[[1.+5.j 0.+2.j 0.+3.j]
 [4.+0.j 5.+0.j 6.+0.j]]


#Bai 11:

In [ ]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6]])
print("Chuyển vị của ma trận:",A.T)


Chuyển vị của ma trận: [[1 4]
 [2 5]
 [3 6]]


#Bài 12:

In [ ]:
import numpy as np

A = np.array([[1, 2],
              [3, 4]])

inv_A = np.linalg.inv(A)

print("\nMa trận nghịch đảo của A:")
print(inv_A)



Ma trận nghịch đảo của A:
[[-2.   1. ]
 [ 1.5 -0.5]]


#Bài 13:

In [ ]:
import numpy as np
M = np.array([[-1,3,2],[0,-2,1],[1,5,-2]])
M_lower = np.tril(M)
print('Ma trận dưới từ dường chéo:',M_lower)


Ma trận dưới từ dường chéo: [[-1  0  0]
 [ 0 -2  0]
 [ 1  5 -2]]


#Bài 14:

In [ ]:
import numpy as np
M = np.array([[-1,3,2],[0,-2,1],[1,5,-2]])
M_upper = np.triu(M)
print('Ma trận trên từ đường chéo:',M_upper)

Ma trận trên từ đường chéo: [[-1  3  2]
 [ 0 -2  1]
 [ 0  0 -2]]


#Bài 15:

In [ ]:
import numpy as np
M = np.array([[-1,3,2],[0,-2,1],[1,5,-2]])
v_diag = np.diag(M) #vectorđường chéo
print (v_diag)
M_diag = np.diag(v_diag)
print (M_diag)

[-1 -2 -2]
[[-1  0  0]
 [ 0 -2  0]
 [ 0  0 -2]]


#Bài 16:


In [ ]:
from sympy import symbols, solve
x,y,z = symbols('x,y,z')
print(solve([x*x+2-6, y-1-6, x+z-1, 2*x*x-8, z*z+4-5, y-z-8], [x,y,z]))

[(2, 7, -1)]


#Bài 17:

In [6]:
import numpy as np
A = np.reshape(np.arange(36.0), (6,6))
print(A)
I6 = np.identity(6)
print(I6)
print(A.size)
print(np.matrix.diagonal(A))
A1 =A + I6
print(A1)

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]
 [24. 25. 26. 27. 28. 29.]
 [30. 31. 32. 33. 34. 35.]]
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
36
[ 0.  7. 14. 21. 28. 35.]
[[ 1.  1.  2.  3.  4.  5.]
 [ 6.  8.  8.  9. 10. 11.]
 [12. 13. 15. 15. 16. 17.]
 [18. 19. 20. 22. 22. 23.]
 [24. 25. 26. 27. 29. 29.]
 [30. 31. 32. 33. 34. 36.]]


#Bài 18:

In [7]:
import numpy as np
A = np.reshape(np.arange(36.0), (6,6))
vecB = np.array([1,2,3,4,5,6])
C =A.dot(vecB)
print(C)

[ 70. 196. 322. 448. 574. 700.]


#Bài 19:


In [11]:
import numpy as np
A = np.reshape(np.arange(36.0), (6,6))
D = np.array([[1., 2., 3., 4., 5., 6.], [1., 0., 1., 0., 1., 0.]])
print(D)
E = D.dot(A)
print(E)

[[1. 2. 3. 4. 5. 6.]
 [1. 0. 1. 0. 1. 0.]]
[[420. 441. 462. 483. 504. 525.]
 [ 36.  39.  42.  45.  48.  51.]]


#Bài 20:


In [12]:
import numpy as np
A = np.reshape(np.arange(36.0), (6,6))
F = np.array([[1., 1.], [2., 0.], [3., 1.], [4., 0], [5., 1], [6., 0.]])
G = A.dot(F)
print (F)
print(G)

[[1. 1.]
 [2. 0.]
 [3. 1.]
 [4. 0.]
 [5. 1.]
 [6. 0.]]
[[ 70.   6.]
 [196.  24.]
 [322.  42.]
 [448.  60.]
 [574.  78.]
 [700.  96.]]


#Bài 21:

In [13]:
import numpy as np
A = np.reshape(np.arange(36.0), (6,6))
print(np.linalg.inv(A))
print(np.linalg.inv(np.linalg.inv(A)))
# do det(A) = 0 nên ma trận không khả nghịch

LinAlgError: Singular matrix

#Bài 22:


In [15]:
import numpy as np
a = np.array([[1,1],[1,0]])
b = np.array([1,0])
n = 10
for i in range(n):
  b = a.dot(b)
print(b)

[89 55]


#Bài 23:


In [16]:
import sympy as sp
from sympy import symbols
x1,x2,x3,x4 = symbols('x1,x2,x3,x4')
from sympy import solve
pt1 = x4+610-450-x1
pt2 = x1+400-x2-640
pt3 = x2+600-x3
pt4 = x3-x4-520
nghiem = sp.solve((pt1,pt2,pt3,pt4))
print(nghiem)

{x1: x4 + 160, x2: x4 - 80, x3: x4 + 520}


#Bài 24:

In [17]:
import numpy as np
A = np.matrix([[-1,0,0,1],[1,-1,0,0],[0,1,-1,0],[0,0,1,-1]])
# Tính ma trận nghịch đảo:
A_nghichdao = np.linalg.inv(A)
print(A_nghichdao)
# Do det(A) = 0 nên ma trận A không khả nghịch

LinAlgError: Singular matrix

# BÀI TẬP VỀ NHÀ

#Bài 1:


In [19]:
import numpy as np
# Vấn đề 1:
A1 = np.array([[1, -1], [2, 3]])
b1 = np.array([-2, 6])

x1 = np.linalg.solve(A1, b1)
print("Vấn đề 1:", x1)
#Vấn đề 2:
A2 = np.array([[1, -1, 0], [2, -1, -1], [1, 1, 1]])
b2 = np.array([2, 3, 6])

x2 = np.linalg.solve(A2, b2)
print("Vấn đề 2:", x2)
#Vấn đề 3:
A3 = np.array([[1, 1, 1], [4, 2, 1], [9, 3, 1]])
b3 = np.array([4, 3, 4])

x3 = np.linalg.solve(A3, b3)
print("Vấn đề 3 (a, b, c):", x3)
#Vấn đề 4:
A4 = np.array([[1, 0, 1], [1, 1, -2], [-2, 2, 1]])
b4 = np.array([1, -3, 0])

x4 = np.linalg.solve(A4, b4)
print("Vấn đề 4 (a, b, c):", x4)


Vấn đề 1: [0. 2.]
Vấn đề 2: [3. 1. 2.]
Vấn đề 3 (a, b, c): [ 1. -4.  7.]
Vấn đề 4 (a, b, c): [-0.11111111 -0.66666667  1.11111111]


#Bài 2:


In [20]:
from sympy import symbols, Eq, solve
# problem 1:
x, y = symbols('x y')

eq1 = Eq(x - y, -2)
eq2 = Eq(2*x + 3*y, 6)

sol1 = solve((eq1, eq2), (x, y))
print("Problem 1 Solution:", sol1)
#problem 2:
x, y, z = symbols('x y z')

eq1 = Eq(x - y, 2)
eq2 = Eq(2*x - y - z, 3)
eq3 = Eq(x + y + z, 6)

sol2 = solve((eq1, eq2, eq3), (x, y, z))
print("Problem 2 Solution:", sol2)
#problem 3:
a, b, c = symbols('a b c')

eq1 = Eq(a + b + c, 4)
eq2 = Eq(4*a + 2*b + c, 3)
eq3 = Eq(9*a + 3*b + c, 4)

sol3 = solve((eq1, eq2, eq3), (a, b, c))
print("Problem 3 Solution:", sol3)
#problem 4:
a, b, c = symbols('a b c')

eq1 = Eq(a + c, 1)
eq2 = Eq(a + b - 2*c, -3)
eq3 = Eq(-2*a + 2*b + c, 0)

sol4 = solve((eq1, eq2, eq3), (a, b, c))
print("Problem 4 Solution:", sol4)


Problem 1 Solution: {x: 0, y: 2}
Problem 2 Solution: {x: 3, y: 1, z: 2}
Problem 3 Solution: {a: 1, b: -4, c: 7}
Problem 4 Solution: {a: -1/9, b: -2/3, c: 10/9}


#Bài 3:

In [21]:
from sympy import Matrix, pprint

def fibonacci_matrix_power(k):
    F = Matrix([[1, 1], [1, 0]])
    Fk = F**k
    return Fk

# Tính F^k và kiểm tra
for k in range(1, 11):
    Fk = fibonacci_matrix_power(k)
    print(f"F^{k} =")
    pprint(Fk)
    print()


F^1 =
⎡1  1⎤
⎢    ⎥
⎣1  0⎦

F^2 =
⎡2  1⎤
⎢    ⎥
⎣1  1⎦

F^3 =
⎡3  2⎤
⎢    ⎥
⎣2  1⎦

F^4 =
⎡5  3⎤
⎢    ⎥
⎣3  2⎦

F^5 =
⎡8  5⎤
⎢    ⎥
⎣5  3⎦

F^6 =
⎡13  8⎤
⎢     ⎥
⎣8   5⎦

F^7 =
⎡21  13⎤
⎢      ⎥
⎣13  8 ⎦

F^8 =
⎡34  21⎤
⎢      ⎥
⎣21  13⎦

F^9 =
⎡55  34⎤
⎢      ⎥
⎣34  21⎦

F^10 =
⎡89  55⎤
⎢      ⎥
⎣55  34⎦

