# BÀI TẬP TRÊN LỚP

Bài 1:

In [2]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
tich = np.inner(a,b) # tích vô hướng
kq = np.dot(a,b)
print (tich)
print(kq)

32
32


Bài 2:

In [5]:
import numpy as np
a = np.array([1,2,-3])
kq = np.linalg.norm(a)
re = np.linalg.norm(a,1)
print(kq)
print(re)

3.7416573867739413
6.0


Bài 2.1:

In [13]:
import math
import numpy as np
a = np.array([1,2,-3])
print('Chuẩn 1 là:',chuan(a, 1))
print('Chuẩn 1 là:',np.linalg.norm(a, 1))
print('Chuẩn 2 là:',chuan(a,2))
print('Chuẩn 2 là:',np.linalg.norm(a,2))
print('Chuẩn 3 là:',chuan(a,3))
print('Chuẩn 3 là:',np.linalg.norm(a,3))
print('Chuẩn 1000 là:',chuan(a,1000))
print('Chuẩn 1000 là:',np.linalg.norm(a,1000))

Chuẩn 1 là: 6.0
Chuẩn 1 là: 6.0
Chuẩn 2 là: 3.7416573867739413
Chuẩn 2 là: 3.7416573867739413
Chuẩn 3 là: 3.3019272488946263
Chuẩn 3 là: 3.3019272488946263
Chuẩn 1000 là: 1.0442214818467515
Chuẩn 1000 là: inf


/usr/local/lib/python3.11/dist-packages/numpy/linalg/_linalg.py:2780: RuntimeWarning: overflow encountered in power
  absx **= ord


Bài 3:

In [14]:
import numpy as np

# Khai báo ma trận A
A = np.array([[0.998, 0.136],
              [0.002, 0.864]])

# Khai báo vector v0 (trạng thái ban đầu)
v0 = np.array([[0.95],
               [0.05]])

# Tính A^100
A_power_100 = np.linalg.matrix_power(A, 100)

# Tính vector sau 100 tuần: v100 = A^100 * v0
v100 = np.dot(A_power_100, v0)

# In kết quả x100 và y100
print("x100 (tỉ lệ thất nghiệp):", v100[0, 0])
print("y100 (tỉ lệ có việc làm):", v100[1, 0])


x100 (tỉ lệ thất nghiệp): 0.9855072337572737
y100 (tỉ lệ có việc làm): 0.01449276624272995


Bài 3.1: Giải bằng gói numpy

In [15]:
import numpy as np

# Hệ phương trình:
# x - 68y = 0
# x + y = 1

# Khai báo ma trận hệ số A và vector B
A = np.array([[1, -68],
              [1, 1]])
B = np.array([0, 1])

# Giải hệ phương trình
solution = np.linalg.solve(A, B)

# Kết quả
x, y = solution
print("x (tỉ lệ thất nghiệp) =", x)
print("y (tỉ lệ có việc làm) =", y)


x (tỉ lệ thất nghiệp) = 0.9855072463768116
y (tỉ lệ có việc làm) = 0.014492753623188406


Bài 3.2: Giải bằng gói sympy

In [16]:
import sympy as sym
from sympy import symbols
x, y = sym.symbols('x y')
xy = sym.Matrix([x,y]) # khai báo vector: (x, y)T
A = sym.Matrix([[1, -68],[1,1]])
v = sym.Matrix([0, 1])
nghiem = sym.solve([A*xy-v]) # phương trình được chuyển về 1 phía
print(sym.pretty(nghiem))

⎧   68         ⎫
⎨x: ──, y: 1/69⎬
⎩   69         ⎭


Bài 3.3:

In [17]:
import numpy as np

# Khai báo ma trận A
A = np.array([[1, 6],
              [5, 2]])

# Khai báo vector riêng u
u = np.array([[6],
              [-5]])

# Tính Au
Au = np.dot(A, u)

# Tính -4u
minus4u = -4 * u

# Kiểm tra
print("A * u =\n", Au)
print("-4 * u =\n", minus4u)

# Kiểm tra xem có bằng nhau không
if np.allclose(Au, minus4u):
    print("=> Đúng, Au = -4u")
else:
    print("=> Sai, Au khác -4u")


A * u =
 [[-24]
 [ 20]]
-4 * u =
 [[-24]
 [ 20]]
=> Đúng, Au = -4u


Bài 3.4:

In [18]:
import sympy
x, y, Lambda = sympy.symbols('x y Lambda')
I = sympy.eye(2)
A = sympy.Matrix([[2,3],[3,-6]])
phuongtrinh = sympy.Eq(sympy.det(Lambda*I-A), 0)
nghiem = sympy.solve(phuongtrinh)
print([sympy.N(phantu,4) for phantu in nghiem])

print (sympy.pretty(nghiem))

[-7.000, 3.000]
[-7, 3]


Bài 3.5:

In [19]:
import numpy as np
A = np.array([[2,3],[3,-6]])
D = np.array([[-7,0],[0,3]])
P = np.array([[-1.0/3, 3],[1,1]])
from numpy import linalg
from numpy import linalg as LA
P1 = LA.inv(P) # tính giá trị nghịch đảo của P
print (P1)
print(A.dot(P))
print( P @ (D ** 1000) @ P1 )
print(D**2)

[[-0.3  0.9]
 [ 0.3  0.1]]
[[ 2.33333333  9.        ]
 [-7.          3.        ]]
[[ 5.03503397e+18  3.50482117e+18]
 [ 3.50482117e+18 -4.31115581e+18]]
[[49  0]
 [ 0  9]]


# BÀI TẬP TRÊN LỚP

Bài 1:

In [22]:
import numpy as np
a = np.array([1,2,3])
mag = np.sqrt(a.dot(a))
print('Câu a:',mag)
mag = np.sqrt(a @ a )
print('Câu b:',mag)
mag = np.sqrt(np.inner(a,a))
print('Câu c:',mag)
mag = lambda x : math.sqrt(sum(i** 2 for i in x))
print('Câu d:',mag(a))

Câu a: 3.7416573867739413
Câu b: 3.7416573867739413
Câu c: 3.7416573867739413
Câu d: 3.7416573867739413


Bài 2:

Câu a:

In [26]:
import numpy as np

# Khai báo vector
u = np.array([3, 4])
v = np.array([1, 0])


# Tính khoảng cách
distance = np.linalg.norm(u - v)

print("Khoảng cách giữa u và v:", distance)


Khoảng cách giữa u và v: 4.47213595499958


Câu b:

In [24]:
import numpy as np
u = np.array([3, 4])
v = np.array([1, 0])

# Tính tích vô hướng
dot_product = np.dot(u, v)

# Tính chuẩn (norm) của u và v
norm_u = np.linalg.norm(u)
norm_v = np.linalg.norm(v)

# Tính cos(θ)
cos_theta = dot_product / (norm_u * norm_v)

# Đảm bảo giá trị cos nằm trong [-1, 1] tránh sai số máy
cos_theta = np.clip(cos_theta, -1.0, 1.0)

# Tính θ (theo radian)
theta = np.arccos(cos_theta)

# Đổi sang độ nếu muốn
theta_degree = np.degrees(theta)

print("Góc giữa u và v (radian):", theta)
print("Góc giữa u và v (độ):", theta_degree)


Góc giữa u và v (radian): 0.9272952180016123
Góc giữa u và v (độ): 53.13010235415599


Câu c:

In [27]:
import numpy as np
u = np.array([3, 4])
v = np.array([1, 0])
# Tính phép chiếu p
p = (np.dot(u, v) / np.dot(v, v)) * v

print("Phép chiếu trực giao của u lên v là:", p)


Phép chiếu trực giao của u lên v là: [3. 0.]
