# ĐỀ THI THỰC HÀNH ĐẠI SỐ TUYẾN TÍNH

Bài 1:

In [17]:
import numpy as np

# Khai báo vector và ma trận
vec_A = np.array([2, -1, 3, 0])
vec_B = np.array([1, 4, -2, 5])


# ---- a) Tính A+B và 3A-2B ----
sum_AB = vec_A + vec_B
scaled = 3 * vec_A - 2 * vec_B

print("a) A + B =", sum_AB)
print("   3A - 2B =", scaled)



a) A + B = [3 3 1 5]
   3A - 2B = [  4 -11  13 -10]


1b:

In [15]:
import numpy as np

# Khai báo vector và ma trận
vec_A = np.array([2, -1, 3, 0])
vec_B = np.array([1, 4, -2, 5])
# ---- b) Tích vô hướng và góc ----
dot_product = np.dot(vec_A, vec_B)
norm_A = np.linalg.norm(vec_A)
norm_B = np.linalg.norm(vec_B)

cos_theta = dot_product / (norm_A * norm_B)
theta_rad = np.arccos(cos_theta)
theta_deg = np.degrees(theta_rad)

print("b) A . B =", dot_product)
print(f"   Góc giữa A và B = {theta_deg:.3f} độ")


b) A . B = -8
   Góc giữa A và B = 108.376 độ


1c:

In [16]:
import numpy as np
mat_C = np.array([
    [1, 2, -1],
    [0, 3, 4],
    [2, -1, 0]
])
# ---- c) Tích ma trận C^T C ----
Ct = mat_C.T
CtC = Ct @ mat_C  # dùng @ thay vì np.dot

print("c) C^T * C =")
print(CtC)


c) C^T * C =
[[ 5  0 -1]
 [ 0 14 10]
 [-1 10 17]]


Bài 2:

In [20]:
import numpy as np

# Khai báo ma trận M và N
M = np.array([
    [1, 2, 3, 0],
    [4, 5, 6, 1],
    [7, 8, 9, 2],
    [0, 1, 1, 0]
])

N = np.array([
    [0, 1, 2, 3],
    [4, 5, 6, 7],
    [8, 9, 10, 11],
    [12, 13, 14, 15]
])

# ---- a) Tính tích ma trận M x N ----
product_MN = M @ N  # hoặc np.dot(M, N)

print("a) Tích M x N =")
print(product_MN)


a) Tích M x N =
[[ 32  38  44  50]
 [ 80  96 112 128]
 [128 154 180 206]
 [ 12  14  16  18]]


2b:

In [18]:
import numpy as np

# Khai báo ma trận M
M = np.array([
    [1, 2, 3, 0],
    [4, 5, 6, 1],
    [7, 8, 9, 2],
    [0, 1, 1, 0]
])
# ---- b) Tính định thức của M ----
try:
    det_M = np.linalg.det(M)
    print(f"\nb) Định thức của M = {det_M:.3f}")
except np.linalg.LinAlgError:
    print("\nb) Không thể tính định thức vì M không là ma trận vuông.")


b) Định thức của M = 0.000


2c:

In [19]:
import numpy as np
N = np.array([
    [0, 1, 2, 3],
    [4, 5, 6, 7],
    [8, 9, 10, 11],
    [12, 13, 14, 15]
])
# ---- c) Tính hạng của ma trận N ----
rank_N = np.linalg.matrix_rank(N)
print(f"\nc) Hạng của N = {rank_N}")


c) Hạng của N = 2


Bài 3:

In [11]:
import numpy as np

# Khai báo ma trận P và vector hằng số b
P = np.array([
    [2, 1, 0, 1],
    [0, 3, 1, -1],
    [1, 0, 4, 2],
    [0, 1, 0, 3]
])

b = np.array([4, 7, 9, 5])  # Vector hằng số từ hệ phương trình

# ---- a) Tìm ma trận nghịch đảo của P ----
try:
    P_inv = np.linalg.inv(P)
    print("a) Ma trận nghịch đảo P^-1 =")
    print(P_inv)
except np.linalg.LinAlgError:
    print("a) Ma trận P không khả nghịch vì định thức bằng 0.")

# ---- b) Giải hệ phương trình bằng nghịch đảo ma trận ----
if 'P_inv' in locals():  # Chỉ thực hiện nếu P khả nghịch
    x = P_inv @ b
    print("\nb) Nghiệm của hệ phương trình (x, y, z, w) =")
    print(x)
else:
    print("\nb) Không thể giải hệ vì P không khả nghịch.")

# ---- c) Kiểm tra nghiệm ----
if 'x' in locals():
    check = P @ x
    print("\nc) Kiểm tra P * nghiệm:")
    print("P * x =", check)
    print("Vector hằng số b =", b)
    print("Có bằng nhau không?", np.allclose(check, b))


a) Ma trận nghịch đảo P^-1 =
[[ 0.48837209 -0.09302326  0.02325581 -0.20930233]
 [ 0.03488372  0.27906977 -0.06976744  0.12790698]
 [-0.11627907  0.06976744  0.23255814 -0.09302326]
 [-0.01162791 -0.09302326  0.02325581  0.29069767]]

b) Nghiệm của hệ phương trình (x, y, z, w) =
[0.46511628 2.10465116 1.65116279 0.96511628]

c) Kiểm tra P * nghiệm:
P * x = [4. 7. 9. 5.]
Vector hằng số b = [4 7 9 5]
Có bằng nhau không? True


Bài 4:

In [12]:
import numpy as np

# Define the matrix Q
Q = np.array([[4, -1, 0],
              [1,  3, -2],
              [0,  1,  2]])

print("Ma trận Q:\n", Q)

# a) Tìm các giá trị riêng (eigenvalues) của Q
eigenvalues, eigenvectors = np.linalg.eig(Q)
print("\n--- a) Giá trị riêng (Eigenvalues) của Q ---")
for i, val in enumerate(eigenvalues):
    print(f"Giá trị riêng {i+1}: {val:.4f}")

# b) Tìm các vector riêng (eigenvectors) tương ứng với các giá trị riêng
print("\n--- b) Vector riêng (Eigenvectors) tương ứng với các giá trị riêng ---")
# The eigenvectors are columns of the matrix 'eigenvectors'
for i, vec in enumerate(eigenvectors.T):  # .T to iterate over columns
    print(f"Vector riêng tương ứng với giá trị riêng {eigenvalues[i]:.4f}:")
    print(vec)

# c) Chuẩn hóa tất cả các vector riêng (độ dài bằng 1)
print("\n--- c) Các Vector riêng đã chuẩn hóa (Normalized Eigenvectors) ---")
normalized_eigenvectors = []
for i, vec in enumerate(eigenvectors.T):
    norm = np.linalg.norm(vec)
    normalized_vec = vec / norm
    normalized_eigenvectors.append(normalized_vec)
    print(f"Vector riêng đã chuẩn hóa {i+1} (tương ứng với giá trị riêng {eigenvalues[i]:.4f}):")
    print(normalized_vec)
    print(f"Độ dài của vector riêng đã chuẩn hóa: {np.linalg.norm(normalized_vec):.4f}")

Ma trận Q:
 [[ 4 -1  0]
 [ 1  3 -2]
 [ 0  1  2]]

--- a) Giá trị riêng (Eigenvalues) của Q ---
Giá trị riêng 1: 3.4534+0.0000j
Giá trị riêng 2: 2.7733+1.4677j
Giá trị riêng 3: 2.7733-1.4677j

--- b) Vector riêng (Eigenvectors) tương ứng với các giá trị riêng ---
Vector riêng tương ứng với giá trị riêng 3.4534+0.0000j:
[0.83327121+0.j 0.455468  +0.j 0.31338154+0.j]
Vector riêng tương ứng với giá trị riêng 2.7733+1.4677j:
[-0.26206044-0.31354813j -0.78166743+0.j         -0.21963176+0.41685708j]
Vector riêng tương ứng với giá trị riêng 2.7733-1.4677j:
[-0.26206044+0.31354813j -0.78166743-0.j         -0.21963176-0.41685708j]

--- c) Các Vector riêng đã chuẩn hóa (Normalized Eigenvectors) ---
Vector riêng đã chuẩn hóa 1 (tương ứng với giá trị riêng 3.4534+0.0000j):
[0.83327121+0.j 0.455468  +0.j 0.31338154+0.j]
Độ dài của vector riêng đã chuẩn hóa: 1.0000
Vector riêng đã chuẩn hóa 2 (tương ứng với giá trị riêng 2.7733+1.4677j):
[-0.26206044-0.31354813j -0.78166743+0.j         -0.21963176+0.

Bài 5:

In [13]:
import numpy as np

# Define the matrix R and vector b
R = np.array([[1, -2, 3],
              [2,  0, 1],
              [-1, 1, 4]])

b = np.array([10, 8, 7])

print("Ma trận R:\n", R)
print("\nVector b:\n", b)

# a) Giải hệ phương trình Rx = b bằng phương pháp np.linalg.solve()
print("\n--- a) Giải hệ phương trình Rx = b bằng np.linalg.solve() ---")
try:
    x_solve = np.linalg.solve(R, b)
    print("Nghiệm x (sử dụng np.linalg.solve()):\n", x_solve)
    # Verify the solution
    print("Kiểm tra: R @ x =", R @ x_solve)
except np.linalg.LinAlgError as e:
    print(f"Lỗi khi giải hệ phương trình: {e}. Ma trận có thể không khả nghịch.")

# b) Xác định xem ma trận R có khả nghịch không.
# Nếu có, tính ma trận nghịch đảo và dùng nó để giải lại hệ. So sánh hai nghiệm.
print("\n--- b) Kiểm tra tính khả nghịch, tính ma trận nghịch đảo và giải lại hệ ---")
try:
    # Calculate the determinant to check invertibility. If determinant is non-zero, it's invertible.
    det_R = np.linalg.det(R)
    print(f"Định thức của R (det(R)): {det_R:.4f}")

    if det_R != 0:
        print("Ma trận R khả nghịch (vì định thức khác 0).")
        R_inv = np.linalg.inv(R)
        print("Ma trận nghịch đảo của R (R_inv):\n", R_inv)

        # Solve the system using the inverse matrix: x = R_inv @ b
        x_inv = R_inv @ b
        print("Nghiệm x (sử dụng ma trận nghịch đảo):\n", x_inv)

        # Compare the two solutions
        print("\nSo sánh hai nghiệm:")
        print("Nghiệm từ np.linalg.solve():", x_solve)
        print("Nghiệm từ ma trận nghịch đảo:", x_inv)
        # Check if they are approximately equal
        if np.allclose(x_solve, x_inv):
            print("Hai nghiệm giống nhau (hoặc rất gần nhau).")
        else:
            print("Hai nghiệm khác nhau.")

    else:
        print("Ma trận R không khả nghịch (vì định thức bằng 0).")

except np.linalg.LinAlgError as e:
    print(f"Lỗi khi tính ma trận nghịch đảo hoặc định thức: {e}. Ma trận có thể suy biến.")

# c) Tính chuẩn Frobenius của ma trận R
print("\n--- c) Chuẩn Frobenius của ma trận R ---")
frobenius_norm_R = np.linalg.norm(R, 'fro')
print(f"Chuẩn Frobenius của ma trận R: {frobenius_norm_R:.4f}")

Ma trận R:
 [[ 1 -2  3]
 [ 2  0  1]
 [-1  1  4]]

Vector b:
 [10  8  7]

--- a) Giải hệ phương trình Rx = b bằng np.linalg.solve() ---
Nghiệm x (sử dụng np.linalg.solve()):
 [2.7826087  0.04347826 2.43478261]
Kiểm tra: R @ x = [10.  8.  7.]

--- b) Kiểm tra tính khả nghịch, tính ma trận nghịch đảo và giải lại hệ ---
Định thức của R (det(R)): 23.0000
Ma trận R khả nghịch (vì định thức khác 0).
Ma trận nghịch đảo của R (R_inv):
 [[-0.04347826  0.47826087 -0.08695652]
 [-0.39130435  0.30434783  0.2173913 ]
 [ 0.08695652  0.04347826  0.17391304]]
Nghiệm x (sử dụng ma trận nghịch đảo):
 [2.7826087  0.04347826 2.43478261]

So sánh hai nghiệm:
Nghiệm từ np.linalg.solve(): [2.7826087  0.04347826 2.43478261]
Nghiệm từ ma trận nghịch đảo: [2.7826087  0.04347826 2.43478261]
Hai nghiệm giống nhau (hoặc rất gần nhau).

--- c) Chuẩn Frobenius của ma trận R ---
Chuẩn Frobenius của ma trận R: 6.0828
