# Bài 1:


In [4]:
import numpy as np
from numpy.linalg import norm
from math import acos, degrees
A = np.array([3,-2,1,4])
B = np.array([-1,5,0,2])
C = np.array([[2,-1,3],[1,4,-2],[0,2,5]])
tong = A+B
tich = 2*A + 3*B
TMT = np.dot(A, B)
goc = TMT / (norm(A) * norm(B))
angle_deg = degrees(acos(goc))
MTC = np.dot(C,C.T)
print(' Câu a')
print('Tổng:',tong)
print('Tích:',tich)
print('\n câu b')
print('A.B:',TMT)
print("Góc giữa A và B =", round(angle_deg, 3), "độ")
print('\n câu c')
print('tích ma trận CCT:',MTC)

 Câu a
Tổng: [2 3 1 6]
Tích: [ 3 11  2 14]

 câu b
A.B: -5
Góc giữa A và B = 99.594 độ

 câu c
tích ma trận CCT: [[14 -8 13]
 [-8 21 -2]
 [13 -2 29]]


#Bài 2:

In [5]:
import numpy as np

# Khởi tạo ma trận M và N
M = np.array([
    [2, -1, 3, 0],
    [1, 4, -2, 5],
    [0, 2, 6, -3],
    [-1, 0, 1, 4]
])

N = np.array([
    [1, 3, -2, 0],
    [4, -1, 5, 2],
    [0, 2, 3, -1],
    [-3, 1, 0, 4]
])

# a) Tính tích M x N
product = np.dot(M, N)
print("a) M x N =\n", product)

# b) Tính định thức của M
try:
    det_M = np.linalg.det(M)
    print("\nb) Định thức của M =", round(det_M, 3))
except np.linalg.LinAlgError:
    print("\nb) Không thể tính định thức của M (không phải ma trận vuông)")

# c) Tính hạng của N
rank_N = np.linalg.matrix_rank(N)
print("\nc) Hạng của N =", rank_N)


a) M x N =
 [[ -2  13   0  -5]
 [  2   0  12  30]
 [ 17   7  28 -14]
 [-13   3   5  15]]

b) Định thức của M = 409.0

c) Hạng của N = 4


# BÀI 3

In [7]:
import numpy as np

# Ma trận P và vector b
P = np.array([
    [3, -1, 0, 2],
    [1, 4, -2, 0],
    [0, 1, 5, -1],
    [2, 0, 1, 3]
], dtype=float)

b = np.array([6, 8, 3, 7], dtype=float)

# a) Tính ma trận nghịch đảo
try:
    P_inv = np.linalg.inv(P)
    print("a) Ma trận nghịch đảo của P:")
    print(np.round(P_inv, 3))
except np.linalg.LinAlgError:
    print("a) Ma trận P không khả nghịch (định thức bằng 0).")

# b) Giải hệ phương trình P @ x = b
x = P_inv @ b
x_rounded = np.round(x, 3)
print("\nb) Nghiệm x của hệ phương trình:")
print("x =", x_rounded)

# c) Kiểm tra lại nghiệm
b_check = P @ x
b_check_rounded = np.round(b_check, 3)
print("\nc) Kiểm tra lại: P @ x =")
print(b_check_rounded)
print("So sánh với vector b =", b)

# Sai số tuyệt đối
diff = np.abs(b - b_check)
print("\n→ Sai số tuyệt đối:", np.round(diff, 6))


a) Ma trận nghịch đảo của P:
[[ 0.5    0.1    0.1   -0.3  ]
 [-0.143  0.2    0.057  0.114]
 [-0.036 -0.05   0.164  0.079]
 [-0.321 -0.05  -0.121  0.507]]

b) Nghiệm x của hệ phương trình:
x = [2.    1.714 0.429 0.857]

c) Kiểm tra lại: P @ x =
[6. 8. 3. 7.]
So sánh với vector b = [6. 8. 3. 7.]

→ Sai số tuyệt đối: [0. 0. 0. 0.]


#BÀI 4

In [12]:
import numpy as np

# Ma trận Q cho trước
Q = np.array([
    [5, -2, 1],
    [0,  3, -1],
    [2,  0, 4]
])

# Tính giá trị riêng và vector riêng
eigenvalues, eigenvectors = np.linalg.eig(Q)

# Làm tròn để dễ nhìn
eigenvalues_rounded = np.round(eigenvalues, 3)
eigenvectors_rounded = np.round(eigenvectors, 3)

# a) Giá trị riêng
print("\n(a) Các giá trị riêng của Q:")
for i, val in enumerate(eigenvalues_rounded):
    print(f"  λ{i+1} = {val}")

# b) Vector riêng ứng với từng giá trị riêng
print("\n(b) Các vector riêng tương ứng:")
for i in range(len(eigenvalues)):
    vec = eigenvectors[:, i]
    print(f"  Vector riêng v{i+1} ứng với λ{i+1} = {eigenvalues_rounded[i]}:")
    print(f"    v{i+1} = {np.round(vec, 3)}")

# c) Chuẩn hóa vector riêng (norm = 1)
print("\n(c) Vector riêng sau khi chuẩn hóa:")
for i in range(len(eigenvalues)):
    vec = eigenvectors[:, i]
    vec_normalized = vec / np.linalg.norm(vec)
    print(f"  v{i+1} chuẩn hóa:")
    print(f"    {np.round(vec_normalized, 3)}")



(a) Các giá trị riêng của Q:
  λ1 = (6.355+0j)
  λ2 = (2.822+1.077j)
  λ3 = (2.822-1.077j)

(b) Các vector riêng tương ứng:
  Vector riêng v1 ứng với λ1 = (6.355+0j):
    v1 = [ 0.748+0.j -0.189+0.j  0.636+0.j]
  Vector riêng v2 ứng với λ2 = (2.822+1.077j):
    v2 = [-0.374+0.342j  0.095+0.574j  0.636+0.j   ]
  Vector riêng v3 ứng với λ3 = (2.822-1.077j):
    v3 = [-0.374-0.342j  0.095-0.574j  0.636-0.j   ]

(c) Vector riêng sau khi chuẩn hóa:
  v1 chuẩn hóa:
    [ 0.748+0.j -0.189+0.j  0.636+0.j]
  v2 chuẩn hóa:
    [-0.374+0.342j  0.095+0.574j  0.636+0.j   ]
  v3 chuẩn hóa:
    [-0.374-0.342j  0.095-0.574j  0.636-0.j   ]


#BÀI 5

In [11]:
import numpy as np

# Dữ liệu đề bài
R = np.array([
    [4, -1, 2],
    [1,  3, -2],
    [0,  2,  5]
])
b = np.array([12, 5, 9])

print("Ma trận R:")
print(R)
print("\nVector b:")
print(b)

# a) Giải hệ phương trình Rx = b
x = np.linalg.solve(R, b)
x_rounded = np.round(x, 3)
print("\n(a) Nghiệm của hệ phương trình Rx = b là:")
print(f"  x = {x_rounded}")

# b) Kiểm tra khả nghịch và giải lại bằng ma trận nghịch đảo
det_R = np.linalg.det(R)
print(f"\n(b) Định thức của R là: det(R) = {np.round(det_R, 3)}")

if det_R != 0:
    R_inv = np.linalg.inv(R)
    x_recomputed = R_inv @ b
    x_recomputed_rounded = np.round(x_recomputed, 3)
    print("\n=> Ma trận R khả nghịch.")
    print("  Ma trận nghịch đảo R⁻¹ là:")
    print(np.round(R_inv, 3))
    print("\n  Giải lại hệ bằng R⁻¹ @ b:")
    print(f"  x' = {x_recomputed_rounded}")
    print("\n  So sánh: x và x' gần như bằng nhau (sai số làm tròn rất nhỏ)")
else:
    print("=> Ma trận R không khả nghịch, không thể giải bằng ma trận nghịch đảo.")

# c) Tính chuẩn Frobenius của ma trận R
fro_norm = np.linalg.norm(R, ord='fro')
print(f"\n(c) Chuẩn Frobenius của ma trận R là: ||R||_F = {np.round(fro_norm, 3)}")


Ma trận R:
[[ 4 -1  2]
 [ 1  3 -2]
 [ 0  2  5]]

Vector b:
[12  5  9]

(a) Nghiệm của hệ phương trình Rx = b là:
  x = [2.788 1.529 1.188]

(b) Định thức của R là: det(R) = 85.0

=> Ma trận R khả nghịch.
  Ma trận nghịch đảo R⁻¹ là:
[[ 0.224  0.106 -0.047]
 [-0.059  0.235  0.118]
 [ 0.024 -0.094  0.153]]

  Giải lại hệ bằng R⁻¹ @ b:
  x' = [2.788 1.529 1.188]

  So sánh: x và x' gần như bằng nhau (sai số làm tròn rất nhỏ)

(c) Chuẩn Frobenius của ma trận R là: ||R||_F = 8.0
