# BÀI TẬP TRÊN LỚP

Bài 1:


In [2]:
import numpy as np
D = np.array([[1,2],[3,4]])
np.copyto(E, D)


NameError: name 'E' is not defined

Bài 1.1:

In [7]:
import numpy as np
E = np.array([[1,2],[3,5]])
np.copyto(E, D)

print(E)

[[1 2]
 [3 4]]


Bài 2:

In [12]:
import numpy as np
x = np.array([['a','b'],['c','d']])
y = 'x'
C = np.asmatrix([[x,y],[1, 2]], dtype = object)
print (C)

[[array([['a', 'b'],
         ['c', 'd']], dtype='<U1') 'x']
 [1 2]]


Bài 2.1:

In [13]:
import numpy as np
A = np.matrix([[[1,2],[3,4]],[[5,6],[7,8]]])
print(A)

ValueError: matrix must be 2-dimensional

Bài 2.2:

In [14]:
import numpy as np
A = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(A)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Bài 3:


In [16]:
from numpy import matlib
G = matlib.identity(5)
print(G)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Bài 3.1:


In [17]:
from numpy import matlib
H = matlib.randn(3,2)
print(H)

[[ 0.15071878 -0.11711085]
 [-0.16029283  1.23066269]
 [-1.56530842 -0.85336721]]


Bài 3.2:

In [18]:
from numpy import matlib
K = matlib.zeros([4,4])
print(K)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Bài 4:


In [22]:
import numpy as np
c = [3, 7, 15, 1, 292, 1, 1, 1, 2, 1, 3, 1, 14, 2] # thử chạy nhiều lần với dãy c dài khác nhau!
M = np.asmatrix([[1,2],[3,4]]) # khởi tạo ma trận 2x2
for i in range(len(c)):
  ci = np.asmatrix([[1,1],[1,0]])
  ci[0, 0] = c[i]
  if (i==0):
    M = ci
  else:
    M = M.dot(ci)
print(M)
print (M[0,0]/M[1,0]) # in số Pi theo dãy số biểu diễn liên phân số

[[165707065  80143857]
 [ 52746197  25510582]]
3.1415926535897936


Bài 5:

In [24]:
import numpy as np
import numpy as np

# Nhập X và Y
X = np.array([[1,1],
              [1, 2],
              [1, 3],
              [1, 4],
              [1, 5]])
Y = np.array([[1],
              [2],
              [4],
              [4],
              [6]])

# Tính XT (X chuyển vị)
XT = X.T

# Tính các giá trị trung gian
A1 = np.linalg.inv(XT.dot(X))   # (X^T X)^-1
A2 = XT.dot(Y)                  # X^T Y

# Tính vector hệ số A = [a0, a1]^T
A = A1.dot(A2)

# In kết quả hệ số
print("Hệ số A =\n", A)
# f_i: giá trị dự đoán
f = X.dot(A)

# Sai số bình phương
error = np.sum((f - Y)**2)
print("Sai số bình phương:", error)


Hệ số A =
 [[-0.2]
 [ 1.2]]
Sai số bình phương: 0.8000000000000003


# BÀI TẬP CHƯƠNG

Bài 1:

In [33]:
import numpy as np

def bpcuctieu(a):  # a là danh sách các giá trị y
    b = []   # lưu giá trị x
    o1 = []  # lưu cột hệ số tự do (toàn số 1)

    for i in range(len(a)):
        o1.append(1.0)
        b.append((i + 1) * 1.0)  # x = 0, 1, 2, ...

    # Tạo ma trận X có dạng [[1, x1], [1, x2], ...]
    x = np.array([o1, b])
    x = x.T  # chuyển vị để đúng dạng m hàng, 2 cột

    # Tính (X^T X)^-1
    u = np.dot(x.T, x)
    u_1 = np.linalg.inv(u)

    # Tính X^T y
    y = np.array(a).reshape(-1, 1)
    v = np.dot(x.T, y)

    # Tính hệ số A = [(a0), (a1)]
    A = np.dot(u_1, v)

    return A

# Dữ liệu y: lượng thuốc còn lại theo từng giờ
dulieu = [10, 8, 7, 5, 2]
A = bpcuctieu(dulieu)

# In ra kết quả
print("Phương trình gần đúng: y =", round(A[0][0], 2), round(A[1][0], 2), "* x")


Phương trình gần đúng: y = 12.1 -1.9 * x
